[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppenlin/contracts=lib/openzeppelin-contracts",  "@foundry-devops/=lib/foundry-devops/src"] 
ffi = true  
fs_permissions = [
    { access = "read", path = "./img/" },
    { access = "read", path = "./broadcast" },
]     

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
